chore: add ci pipe
public-ui/stencil-ds-output-targets pull request #6
Opened 2024-03-11 13:44 UTC by deleonio

2024-03-11 14:53 UTC, sdvg requested changes

2024-03-11 14:53 UTC, sdvg commented on .github/workflows/ci.yml
> +      - name: Install pnpm
Können wir das pnpm-Setup überspringen? Soweit ich sehe nutzen wir nur `npm`.

2024-03-11 14:53 UTC, sdvg commented on .github/workflows/ci.yml
> +        run: npm i --legacy-peer-deps
Mir ist nicht aufgefallen, dass die Option notwendig war, wenn wir sie brauchen würde ich aber vorschlagen, sie in die `.npmrc` einzutragen. Dann müssen wir sie nicht wiederholen und sie wird auch bei der lokalen Entwicklung angewandt.

Außerdem würde ich hier `npm ci` statt `npm i` vorschlagen: https://docs.npmjs.com/cli/v8/commands/npm-ci

2024-03-11 14:53 UTC, sdvg commented on .github/workflows/publish.yml
> +      - name: Install pnpm
Siehe Kommentare in in ci.yml

2024-03-13 09:24 UTC, deleonio commented
@sdvg Ich bekomme das Repo nicht mehr grün, obwohl "meine" Änderungen glaube richtig sind.

Das Problem ist, dass der Build der Apps am Ende mit den neuen Adaptern Probleme macht. Kannst Du Dir das bitte mal anschauen?

Danke

2024-03-14 10:42 UTC, deleonio commented on package.json
> +    "typescript": "^4.9.5"
Das war nicht nicht aufgefallen.

2024-03-14 10:42 UTC, deleonio commented on packages/react-output-target/package.json
> +    "@types/node": "^20.11.27",
Das würde ich auch noch einmal überprüfen.

2024-03-14 13:01 UTC, sdvg approved these changes

2024-03-14 13:32 UTC, merged